# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Duckgpt < Formula
  desc "Ask questions, let GPT do the SQL."
  homepage "https://github.com/cube2222/duckgpt"
  version "0.0.1-prerelease"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cube2222/DuckGPT/releases/download/v0.0.1-prerelease/duckgpt_0.0.1-prerelease_darwin_amd64.tar.gz"
      sha256 "5ea3e3dd37f3e3a6676389acb64d93dee6c5380a8fa8ee0870953478e9ea52a0"

      def install
        bin.install "duckgpt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cube2222/DuckGPT/releases/download/v0.0.1-prerelease/duckgpt_0.0.1-prerelease_darwin_arm64.tar.gz"
      sha256 "6784e46717321410854ebff445b7443ad33fc0099d2dd2726392f122112a3ba7"

      def install
        bin.install "duckgpt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cube2222/DuckGPT/releases/download/v0.0.1-prerelease/duckgpt_0.0.1-prerelease_linux_amd64.tar.gz"
      sha256 "7ad4aa097ff93b147e156fb658abe59a31662201d86ee3e1b0c8d5ce5ab8ad0d"

      def install
        bin.install "duckgpt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cube2222/DuckGPT/releases/download/v0.0.1-prerelease/duckgpt_0.0.1-prerelease_linux_arm64.tar.gz"
      sha256 "22560c40cdefd5c9c12e7bc919b06af6b11e3526cc8bfdf29515754c878e5838"

      def install
        bin.install "duckgpt"
      end
    end
  end

  depends_on "duckdb"
end
