# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Duckgpt < Formula
  desc "Ask questions, let GPT do the SQL."
  homepage "https://github.com/cube2222/duckgpt"
  version "0.1.0"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cube2222/DuckGPT/releases/download/v0.1.0/duckgpt_0.1.0_darwin_amd64.tar.gz"
      sha256 "d1ebc4dc5cdac8ba773a6d1b59e5d6c396beb651f00ce54c09c482488571a88a"

      def install
        bin.install "duckgpt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cube2222/DuckGPT/releases/download/v0.1.0/duckgpt_0.1.0_darwin_arm64.tar.gz"
      sha256 "87943ff8fb15e944ef4e9a2248279a36b8e8d4f035e434777c3e0cf8b69314b4"

      def install
        bin.install "duckgpt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cube2222/DuckGPT/releases/download/v0.1.0/duckgpt_0.1.0_linux_arm64.tar.gz"
      sha256 "d1b70b4e1d677734e7791344d8990ec55e5b7816ea8f508b5a34cf4b95819c43"

      def install
        bin.install "duckgpt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cube2222/DuckGPT/releases/download/v0.1.0/duckgpt_0.1.0_linux_amd64.tar.gz"
      sha256 "df897a881fb1404d53fb6a9f13818ad15297bed548af6b51ed5937d7f5ee8e70"

      def install
        bin.install "duckgpt"
      end
    end
  end

  depends_on "duckdb"
end
